# Generated by Django 5.2.6 on 2025-09-17 02:44

import utils.storages.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.storages.storage.LocalMediaStorage(), upload_to=''),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
